name: Daily Data Analysis # 1. The name of the Factory Line

on:
  push:                   # 2. Trigger: Runs every time you push code
  workflow_dispatch:      # 3. Trigger: Adds a manual "Run Now" button in GitHub UI

jobs:
  analyze-data:           # 4. The Name of the Job
    runs-on: ubuntu-latest # 5. The Worker: We are asking for a Linux machine

    steps:
      # Step A: The worker needs to download your code to its hard drive
      - name: Checkout code
        uses: actions/checkout@v4

      # Step B: We need to install Python on this empty Linux machine
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step C: Install libraries from your requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step D: Run your actual analysis
      # Assumption: Your script saves a file named 'sales_plot.png'
      - name: Run Analysis Script
        run: python src/analysis.py

      # Step E: The "Magic" Step - Save the plot so you can see it!
      # If we don't do this, the worker deletes everything when it finishes.
      - name: Upload Plot as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sales-report-plot
          path: sales_plot.png
